### ISSUE TITLE
False CoDi firmware update available notification while using CosmoCtl

### ISSUE THREAD

**Issue by ZimbiX** [shymega/planet-devices#11]
While using CosmoCtl, I frequently get a notification saying there's a CoDi firmware update available. But there is no update.

![Screenshot_20221212-133648~2](https://user-images.githubusercontent.com/2916331/207578170-27966e9e-712b-454a-b97e-7ab3baa43385.png)

Device: Cosmo Communicator
Android build number: Cosmo-9.0-Planet-02032021-V25

**Comment by shymega** [comment]
CosmoCtl is an unofficial app, and not supported by Planet. I will be closing this issue - whilst there are phantom CoDi update notifications, this seems to be a separate issue.
