### ISSUE TITLE
Rooting-the-Astro doesn't like spaces in paths

### ISSUE THREAD

**Issue by nullman** [shymega/planet-devices#46]
Following the instructions here: https://github.com/shymega/planet-devices/wiki/Rooting-the-Astro
When you run patch.sh, it does not work if your path contains any spaces.
If you accept PR's, I can work on a fix.

**Comment by ZimbiX** [comment]
Go for it, I'd reckon. Either that, or add a note to the instructions that the path should not contain spaces.

**Comment by shymega** [comment]
@ZimbiX made a PR to the wiki, and this can be fixed by forking the wiki PRs repo, making a PR to fix the issue, and I will then merge.

**Comment by nullman** [comment]
> @ZimbiX made a PR to the wiki, and this can be fixed by forking the wiki PRs repo, making a PR to fix the issue, and I will then merge.

Well I took a shot at fixing it and man is it difficult dealing with spaces in shell scripts! I've dealt with them before, but I seem to be having even more difficulty than normal this time.

I think just adding a note in the the wiki that the path needs to not have any spaces should be fine as this is a run-once kind of thing. (So the user can move/rename the directory, perform the patch, then archive wherever.)

**Comment by shymega** [comment]
@nullman Oh, you meant the actual shell script? That's on a different repo. It should handle spaces fine.

**Comment by shymega** [comment]
I think I've fixed it, can you try it again. I'll close the issue again once it's fixed, and if you wanted to make a wiki PR.

**Comment by shymega** [comment]
No, I haven't.

**Comment by shymega** [comment]
Fixed now. I made sure to double quote nearly all variables in the script. `dl_magisk` seems OK.

**Comment by nullman** [comment]
That works! You sir are much better at shell quoting than I am.
