### ISSUE TITLE
Astro Slide: camera quality very poor, autofocus doesn't work

### ISSUE THREAD

**Issue by ThePhilStrongProject** [shymega/planet-devices#5]
Camera quality is far below what is could be with the Sony sensor. Autofocus appears not to work - trying manual focus in OpenCamera does nothing leading me to suspect the focus is fixed to infinity.

**Comment by sobukus** [comment]
Camera focus seems fine for me. A big change from the Gemini, but that is no wonder. I cannot judge for the quality that the sensor should bring elsewhere, but focus seems fine, images with differing resolution seem good.

What's the difference? Maybe you can give some detail on your device. I got a EU/German model with OS build Astro-11.0-Planet-05182022-V01.

**Comment by TauPan** [comment]
There's a thread on this https://www.oesf.org/forum/index.php?topic=36888.0 with examples. I see those weird artifacts as well. Makes camera completely useless.

**Comment by Daz-Mataz** [comment]
I'm getting noticeable improvements to overall camera detail using opencamera since newest firmware release.

**Comment by shymega** [comment]
OK, so given what we've seen thus far with camera improvements, I'd say this issue is resolved.

**Comment by Daz-Mataz** [comment]
I agree that there have been improvements and autofocus does work reliably, however there is still another issue with the camera in certain conditions over edge detecting and then seeming to apply a watercolour filter over the resulting image. Something for another issue I think.

**Comment by shymega** [comment]
Agreed.
