### ISSUE TITLE
Cosmo Communicator Front Camera Image Very Blurry

### ISSUE THREAD

**Issue by outa-time** [shymega/planet-devices#55]
Images from the front camera are very blurry. Not sure if the camera is fixed or auto focus - either way it doesn't work. You can tell it's a person, but not much else. I contacted Planet Computer support and never heard anything back.

**Comment by ZimbiX** [comment]
My Cosmo's front camera works fine (it's fixed focus). Unfortunately, this sounds like a problem with your specific device! 😢 Maybe email them again

**Comment by ZimbiX** [comment]
Let's close this issue, as it's not a widely-applicable problem. I hope Planet Computers get you sorted out without too much hassle 🙂
