### ISSUE TITLE
Right shift key and backspace does not become delete

### ISSUE THREAD

**Issue by wikholm** [shymega/planet-devices#72]
The key in the upper right corner of the keyboard on Planet devices is marked with a left pointing arrow with the word Del above it. Even though the arrow isn't the "proper" backspace symbol, this reasonably indicates that this button is supposed to work as backspace when pressed on its own and as delete in combination with either or both of the shift keys.

When I press the left shift key and backspace, delete works as expected, that is, the character on the right side of the cursor is erased. If I instead press the right shift key and backspace, it behaves like backspace, that is, the character on the left side of the cursor is erased, as if no shift key was pressed. When holding the device in one hand and typing with the other, this makes it unergonomic to use delete.

It doesn't seem to matter which Planet device I'm using. The behaviour consistent across the Gemini, Cosmo and Astro, on their, at the time of writing this, latest officially available Android firmwares. It doesn't seem to matter which app I'm using either. The behaviour seems to be the same wherever I can edit text.

One peculiarity is that if the cursor is at the beginning of the first line in the document or view, then, and only then, does right shift and backspace actually work as delete. That might make this issue a tad harder to notice. Were one to just type something into an empty document and go to the beginning of the line, the right shift key and backspace combination would appear to be flawless.

Pressing both shift keys and backspace also behaves like backspace and not, as expected, delete (except at the beginning of the first line). While it might be unlikely that users would want to press both shift keys, it might still be interesting from an investigative perspective. If a user holds down the left shift key and presses backspace, delete works. If the user keeps holding down the left shift key but then also holds down the right shift key, backspace becomes backspace again (except at the beginning of the first line).

I seem unable to apply labels. If I could, I'd label this issue with Astro-Slide Cosmo-Communicator Gemini-PDA Keyboard-Issue.

**Comment by shymega** [comment]
I'll apply Keyboard issue. Users cannot assign labels, with good reason.

**Comment by Daz-Mataz** [comment]
This has been fixed in the latest V7 firmware
